version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - npm run $COMMAND
      # - npm run sls -- deploy -s $STAGE -r $REGION
      # - npm run acceptance
