version: 0.2

phases:
  build:
    runtime-versions:
      runtime: nodejs10.x
    commands:
      - npm install
      - npm run test
      - npm run sls -- deploy -s $STAGE -r $REGION
      - npm run acceptance
