service: workshop-jacob

plugins:
  - serverless-offline
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action: sns:Publish
      Resource:
        - Ref: restaurantNotificationTopic
        - Ref: restaurantNotificationRetryTopic
        - Ref: restaurantNotificationDLQTopic
    - Effect: Allow
      Action: sns:Publish
      Resource:
        Ref: restaurantNotificationTopic
    - Effect: Allow
      Action: kinesis:PutRecord
      Resource:
        Fn::GetAtt:
          - orderEventsStream
          - Arn
    - Effect: Allow
      Action: dynamodb:scan
      Resource:
        Fn::GetAtt:
          - restaurantsTable
          - Arn
    - Effect: Allow
      Action: execute-api:Invoke
      Resource: arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:*/*/GET/restaurants

functions:
  retry-notify-restaurant:
    handler: functions/retry-notify-restaurant.handler
    events:
      - sns:
          arn:
            Ref: restaurantNotificationRetryTopic
          topicName: ${ssm:/${self:service}/${opt:stage}/restaurant_retry_topic_name}
    environment:
      order_events_stream: ${ssm:/${self:service}/${opt:stage}/stream_name}
      restaurant_notification_topic:
        Ref: restaurantNotificationTopic
    onError:
      Ref: restaurantNotificationDLQTopic
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
    environment:
      orders_api:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.${opt:region}.amazonaws.com/${opt:stage}/orders"
      restaurants_api:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.${opt:region}.amazonaws.com/${opt:stage}/restaurants"
      cognito_user_pool_id: ${ssm:/${self:service}/${opt:stage}/cognito_user_pool_id}
      cognito_client_id: ${ssm:/${self:service}/${opt:stage}/cognito_web_client_id}

  get-restaurants:
    handler: functions/get-restaurants.handler
    events:
      - http:
          path: /restaurants/
          method: get
          authorizer: aws_iam
    environment:
      restaurants_table: ${ssm:/${self:service}/${opt:stage}/table_name}

  search-restaurants:
    handler: functions/search-restaurants.handler
    events:
      - http:
          path: /restaurants/search
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:#{AWS::Region}:#{AWS::AccountId}:userpool/${ssm:/${self:service}/${opt:stage}/cognito_user_pool_id}
    environment:
      restaurants_table: ${ssm:/${self:service}/${opt:stage}/table_name}

  place-order:
    handler: functions/place-order.handler
    events:
      - http:
          path: /orders
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:#{AWS::Region}:#{AWS::AccountId}:userpool/${ssm:/${self:service}/${opt:stage}/cognito_user_pool_id}
    environment:
      order_events_stream: ${ssm:/${self:service}/${opt:stage}/stream_name}

  notify-restaurant:
    handler: functions/notify-restaurant.handler
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - orderEventsStream
              - Arn
    environment:
      order_events_stream: ${ssm:/${self:service}/${opt:stage}/stream_name}
      restaurant_notification_topic:
        Ref: restaurantNotificationTopic
      restaurant_notification_retry_topic:
        Ref: restaurantNotificationRetryTopic

resources:
  Resources:
    restaurantNotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${ssm:/${self:service}/${opt:stage}/restaurant_topic_name}
        TopicName: ${ssm:/${self:service}/${opt:stage}/restaurant_topic_name}
    restaurantNotificationRetryTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${ssm:/${self:service}/${opt:stage}/restaurant_retry_topic_name}
        TopicName: ${ssm:/${self:service}/${opt:stage}/restaurant_retry_topic_name}
    restaurantNotificationDLQTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${ssm:/${self:service}/${opt:stage}/restaurant_dlq_topic_name}
        TopicName: ${ssm:/${self:service}/${opt:stage}/restaurant_dlq_topic_name}
    orderEventsStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${ssm:/${self:service}/${opt:stage}/stream_name}
        ShardCount: 1
    restaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${ssm:/${self:service}/${opt:stage}/table_name}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
